/*
 * build-seo.cjs: writes the machine-readable front door.
 *
 *   node build-seo.cjs
 *
 * This material is meant to be found and reused, by people and by the crawlers that
 * answer people's questions. That needs four things, and all four are GENERATED here
 * rather than typed, for the same reason every figure on the site is read out of the
 * data files at load time: a distance hand-copied into a meta tag is a distance that
 * drifts the first time the sheet moves, and nothing would fail.
 *
 *   robots.txt    every crawler allowed, the AI ones named explicitly, sitemap declared
 *   sitemap.xml   the two pages and the six data files, so the JSON is crawlable too
 *   llms.txt      the llmstxt.org convention: one markdown page describing the whole set
 *   JSON-LD       schema.org graphs injected into index.html and booklet.html
 *
 * The JSON-LD is INJECTED, not fetched. index.html and booklet.html build their own
 * figures from template.json at load time, which is right for a reader with a browser
 * and useless to a crawler that does not run scripts. So the numbers are baked into a
 * <script type="application/ld+json"> block between markers, and this script is what
 * puts them there. Re-running is idempotent: the markers are replaced, not appended.
 *
 * Run it after build-template.cjs or build-route.cjs. `node --test` fails if the
 * injected figures no longer match the data files, so a stale block cannot ship.
 */

const fs = require('fs');

const BASE = 'https://thegreatindiaride.prasanthsasikumar.com';
const AUTHOR = 'Prasanth Sasikumar';
const AUTHOR_URL = 'https://prasanthsasikumar.com';

const BEGIN = '<!-- BEGIN ld+json: generated by build-seo.cjs, do not edit by hand -->';
const END = '<!-- END ld+json -->';

// Named rather than left to the wildcard. A bare `User-agent: *` does allow all of
// these, but several of these operators publish their token precisely so a site can
// state a position, and "allowed, deliberately" is a different statement from "never
// considered". This material is published to be quoted; being quoted with attribution
// is the point. Keep the list; do not trim it to the ones in the news this month.
const AI_AGENTS = [
  'GPTBot', 'OAI-SearchBot', 'ChatGPT-User',
  'ClaudeBot', 'Claude-User', 'Claude-SearchBot', 'anthropic-ai',
  'Google-Extended', 'Googlebot', 'Bingbot', 'Applebot', 'Applebot-Extended',
  'PerplexityBot', 'Perplexity-User',
  'CCBot', 'Amazonbot', 'Bytespider', 'cohere-ai', 'Meta-ExternalAgent',
  'DuckAssistBot', 'MistralAI-User', 'Diffbot', 'Timpibot',
];

// Every published data file, with the sentence that says what a reader gets by
// fetching it. These same descriptions print on the closing page of the route book;
// this is the second audience for them, not a second copy of them, so if one changes
// the other should be looked at.
const DATA_FILES = [
  ['template.json', 'The planned loop: five sectors, 97 hops, every waypoint with coordinates, distance and riding hours. This is the file to fork if you want to plan your own route.'],
  ['template-notes.json', 'The hand-written guidance: riding seasons, permits, points of interest. Entries reading TO WRITE are unwritten and render as a visible gap.'],
  ['route.json', 'The ride as actually run: 93 nights, every place slept, and what was spent.'],
  ['research.json', 'Field research into the xBhp "The Tourer" archive, India\'s oldest motorcycling forum, transcribed with its own caveats attached.'],
  ['k2k.json', 'Kanyakumari to Kashmir as two lines, one cited and one measured, with the provenance of every coordinate.'],
  ['basemap.json', 'Country outlines for the maps, from Natural Earth\'s India point-of-view file.'],
  ['manifest.json', 'The media library: 222 clips from the ride, with capture time, region and caption.'],
];

function read(p) { return JSON.parse(fs.readFileSync(p, 'utf8')); }
function fmt(n) { return n.toLocaleString('en-IN'); }

/* ─── robots.txt ─────────────────────────────────────────────────────────── */

function robots() {
  const lines = [
    '# Everything here is published to be read, quoted and reused, by people and by',
    '# machines. Attribution is asked for and not enforced; the research plates under',
    '# /media/research/ are other riders\' photographs and are credited per image, so',
    '# those carry somebody else\'s rights and not ours.',
    '#',
    '# See /llms.txt for what this site is and which file holds what.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
  ];
  AI_AGENTS.forEach(function (a) {
    lines.push('User-agent: ' + a);
    lines.push('Allow: /');
    lines.push('');
  });
  lines.push('Sitemap: ' + BASE + '/sitemap.xml');
  lines.push('');
  return lines.join('\n');
}

/* ─── sitemap.xml ────────────────────────────────────────────────────────── */

function sitemap(day) {
  const urls = [
    [BASE + '/', '1.0'],
    [BASE + '/booklet.html', '0.9'],
    [BASE + '/llms.txt', '0.5'],
  ];
  // The data files are listed too. A sitemap is usually pages only, but here the JSON
  // IS the deliverable: someone forking the loop wants template.json, not a screenshot
  // of it, and a crawler that never sees the file cannot tell anyone it exists.
  DATA_FILES.forEach(function (f) { urls.push([BASE + '/' + f[0], '0.6']); });

  const out = ['<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'];
  urls.forEach(function (u) {
    out.push('  <url>');
    out.push('    <loc>' + u[0] + '</loc>');
    out.push('    <lastmod>' + day + '</lastmod>');
    out.push('    <priority>' + u[1] + '</priority>');
    out.push('  </url>');
  });
  out.push('</urlset>');
  out.push('');
  return out.join('\n');
}

/* ─── llms.txt ───────────────────────────────────────────────────────────── */

function llms(tpl, route, notes, research) {
  const t = tpl.totals;
  const sectors = tpl.sectors.map(function (s) {
    return '- **' + s.id + ', ' + s.title + '** (' + s.from + ' to ' + s.to + '): ' +
      fmt(s.km) + ' km, ' + Math.round(s.hours) + ' riding hours.';
  });

  const gaps = countGaps(notes);

  return [
    '# The Great India Ride',
    '',
    '> An ' + fmt(t.km) + ' km motorcycle loop of India, published as a reusable route',
    '> template and not only as a travelogue: ' + t.hops + ' hops, ' + t.waypoints + ' way' +
      'points, ' + tpl.sectors.length + ' sectors, ' + t.countries + ' countries, with',
    '> every coordinate, distance and riding hour in machine-readable JSON on a',
    '> CORS-open host. It was ridden over ' + route.nights + ' nights across ' +
      route.totals.regions + ' regions of India, Nepal and Bhutan.',
    '',
    'Two things are published here and they are not the same thing. `route.json` is what',
    'happened. `template.json` is the loop as it was drawn, and it is the one to fork:',
    'the sector boundaries fall at the two cities the loop returns to (Bengaluru and',
    'Delhi), which are exactly the places a rider can join the loop or leave it. Take a',
    'sector, take two, or take the whole thing.',
    '',
    '## The loop',
    '',
  ].concat(sectors).concat([
    '',
    'Totals: ' + fmt(t.km) + ' km, ' + fmt(t.hours) + ' riding hours, ' + t.hops +
      ' hops. The two figures a reader is most likely to question are disclosed on the',
    'page rather than smoothed: the sheet\'s own total row says 18,039.2 km against the',
    '18,181.3 km its rows sum to, and one hop (Agartala to Kolkata, 1,523 km) is the',
    'sheet routing around the Bangladesh border and is not a rideable day.',
    '',
    '## Pages',
    '',
    '- [The ride](' + BASE + '/): the journey told in the order it happened, with the',
    '  map, the media library, and the planned loop drawn under the ridden one.',
    '- [The route book](' + BASE + '/booklet.html): the printable version. Sector maps,',
    '  waypoint tables, the cost projection, the season and permit calendar, blank',
    '  planning pages, and the field research appendix.',
    '',
    '## Data',
    '',
    'All files are served from ' + BASE + ' with CORS enabled. Fetch them directly.',
    '',
  ]).concat(DATA_FILES.map(function (f) {
    return '- [' + f[0] + '](' + BASE + '/' + f[0] + '): ' + f[1];
  })).concat([
    '',
    '## What this material does not claim',
    '',
    '- **The seasons and most of the permits are unwritten.** ' + gaps + ' guidance',
    '  notes in `template-notes.json` are empty, and every one of them renders on the',
    '  page as a dashed box reading "Not written yet", never as filler text.',
    '  A route book is acted on, so an admitted hole is better than invented advice.',
    '  The field research found that pan-India riders time their trips by leave rather',
    '  than by weather, so nothing in that archive could be used to fill them in.',
    '- **The cost projection is a floor, not a forecast.** It applies rates observed on',
    '  the real ride to the template\'s shape, budgets no rest days, and carries no bike,',
    '  no shipping, no flights and no repairs.',
    '- **Permits change.** The Inner Line Permit note for the Northeast reflects sources',
    '  read in 2025. Check the current rules before you ride.',
    '- **The forum counts are keyword-derived.** ' + research.corpus.indexPages +
      ' index pages and ' + fmt(research.corpus.threads) + ' threads were crawled, of',
    '  which ' + research.corpus.readInFull + ' pan-India ride reports were read end to',
    '  end. The aggregate counts come from matching URL slugs and are a picture of',
    '  proportion, not a census. The report\'s own caveats travel with the figures.',
    '',
    '## Reuse',
    '',
    'The route data, the build scripts and the pages are free to fork and adapt; the',
    'source is at https://github.com/prasanthsasikumar/thegreatindiaride. The eight',
    'photographs under `/media/research/` are other riders\' work, reproduced with their',
    'watermarks intact and a per-image credit, and are not covered by that. Ride media',
    'under `/media/` is ' + AUTHOR + '\'s.',
    '',
  ]).join('\n');
}

// booklet.html's own predicate, verbatim: a note is unwritten if it is empty or starts
// with TO WRITE. Counted here rather than stated, so the number in llms.txt moves when
// somebody actually writes one.
//
// This counts DISTINCT unwritten notes (10 today: five seasons, four permits, and the
// planned-versus-ridden note), not the 15 dashed boxes the book prints. The book prints
// each unwritten season twice, once on its sector spread and once in the calendar, and
// test/booklet.test.cjs pins that 15 because it is asserting against the rendering. A
// crawler summarising this material wants to know how much guidance is missing, not how
// many times the page admits it.
function countGaps(notes) {
  const written = function (s) { return !!s && String(s).indexOf('TO WRITE') !== 0; };
  const sectors = notes.sectors || {};
  let n = 0;
  Object.keys(sectors).forEach(function (id) {
    if (!written(sectors[id].season)) n++;
    if (!written(sectors[id].permits)) n++;
  });
  if (!written(notes.plannedVsRidden)) n++;
  if (!written(notes.sourcing)) n++;
  return n;
}

/* ─── JSON-LD ────────────────────────────────────────────────────────────── */

function person() {
  return {
    '@type': 'Person',
    '@id': BASE + '/#author',
    name: AUTHOR,
    url: AUTHOR_URL,
    sameAs: ['https://www.instagram.com/thegreatindiaride/'],
  };
}

// One TouristTrip for the loop, with its sectors as the itinerary. This is the entity
// the whole site is about, so both pages point at the same @id rather than each
// describing a trip of its own.
function trip(tpl, route) {
  const t = tpl.totals;
  return {
    '@type': 'TouristTrip',
    '@id': BASE + '/#loop',
    name: 'The Great India Ride: a pan-India motorcycle loop',
    description: 'A ' + fmt(t.km) + ' km motorcycle loop of India in ' + t.sectors +
      ' sectors, drawn as a reusable route template. ' + t.hops + ' hops across ' +
      t.countries + ' countries, ridden over ' + route.nights + ' nights.',
    url: BASE + '/',
    author: { '@id': BASE + '/#author' },
    provider: { '@id': BASE + '/#author' },
    touristType: ['Motorcycle touring', 'Adventure motorcycling', 'Long-distance riding'],
    distance: { '@type': 'Distance', name: fmt(t.km) + ' km' },
    subjectOf: { '@id': BASE + '/booklet.html#routebook' },
    itinerary: {
      '@type': 'ItemList',
      numberOfItems: tpl.sectors.length,
      itemListElement: tpl.sectors.map(function (s, i) {
        return {
          '@type': 'ListItem',
          position: i + 1,
          item: {
            '@type': 'TouristTrip',
            name: s.id + ': ' + s.title,
            description: s.from + ' to ' + s.to + ', ' + fmt(s.km) + ' km and ' +
              Math.round(s.hours) + ' riding hours.',
            distance: { '@type': 'Distance', name: fmt(s.km) + ' km' },
            itinerary: [
              { '@type': 'Place', name: s.from },
              { '@type': 'Place', name: s.to },
            ],
          },
        };
      }),
    },
  };
}

// The JSON files, described as a Dataset with one DataDownload per file. This is the
// part that makes the material fetchable rather than merely readable: a crawler that
// understands schema.org gets the URL, the MIME type and a sentence about each file.
function dataset(tpl) {
  const t = tpl.totals;
  return {
    '@type': 'Dataset',
    '@id': BASE + '/#dataset',
    name: 'Pan-India motorcycle route template and ride record',
    description: 'Machine-readable route data for a ' + fmt(t.km) + ' km motorcycle ' +
      'loop of India, Nepal and Bhutan: ' + t.waypoints + ' waypoints with coordinates, ' +
      t.hops + ' hops with distance and riding hours, the sectors they divide into, the ' +
      'nights and spend of the ride that was actually run, and transcribed field ' +
      'research from the xBhp forum archive.',
    url: BASE + '/',
    license: 'https://github.com/prasanthsasikumar/thegreatindiaride',
    creator: { '@id': BASE + '/#author' },
    isAccessibleForFree: true,
    keywords: [
      'motorcycle touring India', 'pan-India ride', 'all India motorcycle trip',
      'route template', 'Kanyakumari to Kashmir', 'K2K', 'Ladakh',
      'Northeast India Inner Line Permit', 'GPS waypoints', 'itinerary',
    ],
    spatialCoverage: [
      { '@type': 'Place', name: 'India' },
      { '@type': 'Place', name: 'Nepal' },
      { '@type': 'Place', name: 'Bhutan' },
    ],
    distribution: DATA_FILES.map(function (f) {
      return {
        '@type': 'DataDownload',
        name: f[0],
        description: f[1],
        contentUrl: BASE + '/' + f[0],
        encodingFormat: 'application/json',
      };
    }),
  };
}

function indexGraph(tpl, route) {
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebSite',
        '@id': BASE + '/#website',
        url: BASE + '/',
        name: 'The Great India Ride',
        description: '100 days and ' + fmt(tpl.totals.km) + ' km around India on one ' +
          'motorcycle, told in the order it happened and published as a route template ' +
          'anyone can fork.',
        inLanguage: 'en',
        publisher: { '@id': BASE + '/#author' },
      },
      person(),
      trip(tpl, route),
      dataset(tpl),
    ],
  };
}

function bookletGraph(tpl, route, notes) {
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'TechArticle',
        '@id': BASE + '/booklet.html#routebook',
        url: BASE + '/booklet.html',
        headline: 'The route book for the pan-India loop',
        description: 'A printable route book for a ' + fmt(tpl.totals.km) + ' km ' +
          'pan-India motorcycle loop: sector maps, waypoint tables with coordinates ' +
          'and riding hours, a cost projection derived from the ride that was run, a ' +
          'season and permit calendar, blank planning pages, and a field research ' +
          'appendix from the xBhp archive.',
        inLanguage: 'en',
        author: { '@id': BASE + '/#author' },
        about: { '@id': BASE + '/#loop' },
        isBasedOn: { '@id': BASE + '/#dataset' },
        // Stated because the book states it to its reader, in a dashed box on the page.
        // A crawler summarising this material should be able to see the same hole.
        disambiguatingDescription: countGaps(notes) + ' guidance entries (riding ' +
          'seasons and some permit notes) are unwritten and appear on the page as an ' +
          'explicit gap rather than as filler.',
      },
      person(),
      trip(tpl, route),
      dataset(tpl),
    ],
  };
}

/* ─── injection ──────────────────────────────────────────────────────────── */

function inject(file, graph) {
  const html = fs.readFileSync(file, 'utf8');
  const block = BEGIN + '\n<script type="application/ld+json">\n' +
    JSON.stringify(graph, null, 1) + '\n</script>\n' + END;

  const i = html.indexOf(BEGIN);
  const j = html.indexOf(END);
  let out;
  if (i !== -1 && j !== -1) {
    out = html.slice(0, i) + block + html.slice(j + END.length);
  } else {
    // First run: land it just before the stylesheet, which is where the rest of the
    // head's metadata already is.
    const anchor = '<style>';
    const k = html.indexOf(anchor);
    if (k === -1) throw new Error(file + ': no <style> to anchor the block to');
    out = html.slice(0, k) + block + '\n' + html.slice(k);
  }
  fs.writeFileSync(file, out);
  console.log(file + ': ld+json ' + (i === -1 ? 'inserted' : 'refreshed') +
    ' (' + JSON.stringify(graph).length + ' bytes)');
}

/* ─── main ───────────────────────────────────────────────────────────────── */

function main() {
  const tpl = read('template.json');
  const route = read('route.json');
  const notes = read('template-notes.json');
  const research = read('research.json');

  const day = new Date().toISOString().slice(0, 10);

  fs.writeFileSync('robots.txt', robots());
  console.log('robots.txt: ' + AI_AGENTS.length + ' agents named, sitemap declared');

  fs.writeFileSync('sitemap.xml', sitemap(day));
  console.log('sitemap.xml: ' + (3 + DATA_FILES.length) + ' urls');

  fs.writeFileSync('llms.txt', llms(tpl, route, notes, research));
  console.log('llms.txt: written');

  inject('index.html', indexGraph(tpl, route));
  inject('booklet.html', bookletGraph(tpl, route, notes));
}

if (require.main === module) main();

module.exports = {
  BASE, DATA_FILES, AI_AGENTS, BEGIN, END,
  robots, sitemap, llms, indexGraph, bookletGraph, countGaps,
};
